// Generated by delombok at Thu Apr 10 14:09:06 PDT 2025
package com.fasterxml.jackson.datatype.javax.money;

import javax.money.MonetaryAmount;

public class SchemaTestClass {
    private final MonetaryAmount moneyOne;
    private final MonetaryAmount moneyTwo;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public SchemaTestClass(final MonetaryAmount moneyOne, final MonetaryAmount moneyTwo) {
        this.moneyOne = moneyOne;
        this.moneyTwo = moneyTwo;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public MonetaryAmount getMoneyOne() {
        return this.moneyOne;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public MonetaryAmount getMoneyTwo() {
        return this.moneyTwo;
    }
}
