// Generated by delombok at Thu Apr 10 13:56:11 PDT 2025
package tools.jackson.datatype.javax.money;

public final class FieldNames {
    static final FieldNames DEFAULT = FieldNames.valueOf("amount", "currency", "formatted");
    private final String amount;
    private final String currency;
    private final String formatted;

    public static FieldNames defaults() {
        return DEFAULT;
    }

    //@lombok.Generated
    private FieldNames(final String amount, final String currency, final String formatted) {
        this.amount = amount;
        this.currency = currency;
        this.formatted = formatted;
    }

    //@lombok.Generated
    public static FieldNames valueOf(final String amount, final String currency, final String formatted) {
        return new FieldNames(amount, currency, formatted);
    }

    //@lombok.Generated
    public String getAmount() {
        return this.amount;
    }

    //@lombok.Generated
    public String getCurrency() {
        return this.currency;
    }

    //@lombok.Generated
    public String getFormatted() {
        return this.formatted;
    }

    /**
     * @return a clone of this object, except with this updated property (returns {@code this} if an identical value is passed).
     */
    //@lombok.Generated
    public FieldNames withAmount(final String amount) {
        return this.amount == amount ? this : new FieldNames(amount, this.currency, this.formatted);
    }

    /**
     * @return a clone of this object, except with this updated property (returns {@code this} if an identical value is passed).
     */
    //@lombok.Generated
    public FieldNames withCurrency(final String currency) {
        return this.currency == currency ? this : new FieldNames(this.amount, currency, this.formatted);
    }

    /**
     * @return a clone of this object, except with this updated property (returns {@code this} if an identical value is passed).
     */
    //@lombok.Generated
    public FieldNames withFormatted(final String formatted) {
        return this.formatted == formatted ? this : new FieldNames(this.amount, this.currency, formatted);
    }
}
